export const GET_TAX_PAYER = "GET_TAX_PAYER"
export const GET_TAX_PAYER_SUCCESS = "GET_TAX_PAYER_SUCCESS"
export const GET_TAX_PAYER_FAILED = "GET_TAX_PAYER_FAILED"

export const ADD_TAX_PAYER = "ADD_TAX_PAYER"
export const ADD_TAX_PAYER_SUCCESS = "ADD_TAX_PAYER_SUCCESS"
export const ADD_TAX_PAYER_FAILED = "ADD_TAX_PAYER_FAILED"

export const UPDATE_TAX_PAYER = "UPDATE_TAX_PAYER"
export const UPDATE_TAX_PAYER_SUCCESS = "UPDATE_TAX_PAYER_SUCCESS"
export const UPDATE_TAX_PAYER_FAILED = "UPDATE_TAX_PAYER_FAILED"

export const DELETE_TAX_PAYER = "DELETE_TAX_PAYER"
export const DELETE_TAX_PAYER_SUCCESS = "DELETE_TAX_PAYER_SUCCESS"
export const DELETE_TAX_PAYER_FAILED = "DELETE_TAX_PAYER_FAILED"